# Generated by cabin authoring. Adapt FROM to your project base image.
FROM tuto2-web

ARG OPENCODE_VERSION=1.4.9
# Define the agent version as a build argument
ARG PI_VERSION=v0.72.1

# Install all required packages in one step
RUN apt-get update && apt-get install -y \
    git \
    iproute2 \
    sqlite3 \
    curl \
    vim \
    ca-certificates \
    bash-completion \
    less \
    bubblewrap \
    socat \
    strace \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Copy the materialized fragments to a build dir and run the numbered install steps
COPY .deps/ /opt/ai-cabin-deps/
RUN /bin/sh /opt/ai-cabin-deps/install.sh \
 && rm -rf /opt/ai-cabin-deps
ENTRYPOINT ["/docker-entrypoint.sh"]

# User setup (the root-to-user transition stays visible here on purpose)
RUN useradd -m ai_agent
WORKDIR /home/ai_agent
# Own the whole home so the agent can write anywhere it needs
RUN chown -R ai_agent:ai_agent /home/ai_agent
USER ai_agent
WORKDIR /home/ai_agent

# Add a greywall sandbox indicator to the prompt
RUN echo 'if [ "$GREYWALL_SANDBOX" = "1" ]; then debian_chroot="🔒"; fi' >> /home/ai_agent/.bashrc

# Create future mount-points so their owner is ai_agent
RUN mkdir -p .local/share .local/state .local/bin .cache .config/greywall desk go
# Agent opencode: web UI (install.d/50-opencode reads OPENCODE_VERSION)
RUN mkdir -p .config/opencode
EXPOSE 9090
CMD ["opencode", "web", "--port", "9090", "--hostname", "0.0.0.0"]
# Agent pi: pi-dev session + ripgrep + fd (install.d/50-pi reads PI_VERSION)
RUN mkdir -p .pi/agent

