// Code generated by mockery. DO NOT EDIT.

package mock_config

import mock "github.com/stretchr/testify/mock"

// HomeDirProvider is an autogenerated mock type for the HomeDirProvider type
type HomeDirProvider struct {
	mock.Mock
}

type HomeDirProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *HomeDirProvider) EXPECT() *HomeDirProvider_Expecter {
	return &HomeDirProvider_Expecter{mock: &_m.Mock}
}

// GetHomeDir provides a mock function with no fields
func (_m *HomeDirProvider) GetHomeDir() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHomeDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeDirProvider_GetHomeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHomeDir'
type HomeDirProvider_GetHomeDir_Call struct {
	*mock.Call
}

// GetHomeDir is a helper method to define mock.On call
func (_e *HomeDirProvider_Expecter) GetHomeDir() *HomeDirProvider_GetHomeDir_Call {
	return &HomeDirProvider_GetHomeDir_Call{Call: _e.mock.On("GetHomeDir")}
}

func (_c *HomeDirProvider_GetHomeDir_Call) Run(run func()) *HomeDirProvider_GetHomeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HomeDirProvider_GetHomeDir_Call) Return(_a0 string, _a1 error) *HomeDirProvider_GetHomeDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeDirProvider_GetHomeDir_Call) RunAndReturn(run func() (string, error)) *HomeDirProvider_GetHomeDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewHomeDirProvider creates a new instance of HomeDirProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHomeDirProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *HomeDirProvider {
	mock := &HomeDirProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
