// Code generated by mockery. DO NOT EDIT.

package mock_config

import mock "github.com/stretchr/testify/mock"

// GitConfigProvider is an autogenerated mock type for the GitConfigProvider type
type GitConfigProvider struct {
	mock.Mock
}

type GitConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *GitConfigProvider) EXPECT() *GitConfigProvider_Expecter {
	return &GitConfigProvider_Expecter{mock: &_m.Mock}
}

// GetUserEmail provides a mock function with no fields
func (_m *GitConfigProvider) GetUserEmail() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserEmail")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GitConfigProvider_GetUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserEmail'
type GitConfigProvider_GetUserEmail_Call struct {
	*mock.Call
}

// GetUserEmail is a helper method to define mock.On call
func (_e *GitConfigProvider_Expecter) GetUserEmail() *GitConfigProvider_GetUserEmail_Call {
	return &GitConfigProvider_GetUserEmail_Call{Call: _e.mock.On("GetUserEmail")}
}

func (_c *GitConfigProvider_GetUserEmail_Call) Run(run func()) *GitConfigProvider_GetUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GitConfigProvider_GetUserEmail_Call) Return(_a0 string, _a1 error) *GitConfigProvider_GetUserEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GitConfigProvider_GetUserEmail_Call) RunAndReturn(run func() (string, error)) *GitConfigProvider_GetUserEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserName provides a mock function with no fields
func (_m *GitConfigProvider) GetUserName() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GitConfigProvider_GetUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserName'
type GitConfigProvider_GetUserName_Call struct {
	*mock.Call
}

// GetUserName is a helper method to define mock.On call
func (_e *GitConfigProvider_Expecter) GetUserName() *GitConfigProvider_GetUserName_Call {
	return &GitConfigProvider_GetUserName_Call{Call: _e.mock.On("GetUserName")}
}

func (_c *GitConfigProvider_GetUserName_Call) Run(run func()) *GitConfigProvider_GetUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GitConfigProvider_GetUserName_Call) Return(_a0 string, _a1 error) *GitConfigProvider_GetUserName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GitConfigProvider_GetUserName_Call) RunAndReturn(run func() (string, error)) *GitConfigProvider_GetUserName_Call {
	_c.Call.Return(run)
	return _c
}

// NewGitConfigProvider creates a new instance of GitConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitConfigProvider {
	mock := &GitConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
