// Code generated by mockery. DO NOT EDIT.

package mock_config

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// FileWriter is an autogenerated mock type for the FileWriter type
type FileWriter struct {
	mock.Mock
}

type FileWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *FileWriter) EXPECT() *FileWriter_Expecter {
	return &FileWriter_Expecter{mock: &_m.Mock}
}

// WriteFile provides a mock function with given fields: path, data, perm
func (_m *FileWriter) WriteFile(path string, data []byte, perm os.FileMode) error {
	ret := _m.Called(path, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = rf(path, data, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileWriter_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type FileWriter_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path string
//   - data []byte
//   - perm os.FileMode
func (_e *FileWriter_Expecter) WriteFile(path interface{}, data interface{}, perm interface{}) *FileWriter_WriteFile_Call {
	return &FileWriter_WriteFile_Call{Call: _e.mock.On("WriteFile", path, data, perm)}
}

func (_c *FileWriter_WriteFile_Call) Run(run func(path string, data []byte, perm os.FileMode)) *FileWriter_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(os.FileMode))
	})
	return _c
}

func (_c *FileWriter_WriteFile_Call) Return(_a0 error) *FileWriter_WriteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileWriter_WriteFile_Call) RunAndReturn(run func(string, []byte, os.FileMode) error) *FileWriter_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileWriter creates a new instance of FileWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileWriter {
	mock := &FileWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
