// Code generated by mockery. DO NOT EDIT.

package mock_fs

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// StatFS is an autogenerated mock type for the StatFS type
type StatFS struct {
	mock.Mock
}

type StatFS_Expecter struct {
	mock *mock.Mock
}

func (_m *StatFS) EXPECT() *StatFS_Expecter {
	return &StatFS_Expecter{mock: &_m.Mock}
}

// Open provides a mock function with given fields: name
func (_m *StatFS) Open(name string) (fs.File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type StatFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *StatFS_Expecter) Open(name interface{}) *StatFS_Open_Call {
	return &StatFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *StatFS_Open_Call) Run(run func(name string)) *StatFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StatFS_Open_Call) Return(_a0 fs.File, _a1 error) *StatFS_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatFS_Open_Call) RunAndReturn(run func(string) (fs.File, error)) *StatFS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: name
func (_m *StatFS) Stat(name string) (fs.FileInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatFS_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type StatFS_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *StatFS_Expecter) Stat(name interface{}) *StatFS_Stat_Call {
	return &StatFS_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *StatFS_Stat_Call) Run(run func(name string)) *StatFS_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StatFS_Stat_Call) Return(_a0 fs.FileInfo, _a1 error) *StatFS_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatFS_Stat_Call) RunAndReturn(run func(string) (fs.FileInfo, error)) *StatFS_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewStatFS creates a new instance of StatFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatFS {
	mock := &StatFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
