// Code generated by mockery. DO NOT EDIT.

package mock_fs

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// ReadDirFS is an autogenerated mock type for the ReadDirFS type
type ReadDirFS struct {
	mock.Mock
}

type ReadDirFS_Expecter struct {
	mock *mock.Mock
}

func (_m *ReadDirFS) EXPECT() *ReadDirFS_Expecter {
	return &ReadDirFS_Expecter{mock: &_m.Mock}
}

// Open provides a mock function with given fields: name
func (_m *ReadDirFS) Open(name string) (fs.File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadDirFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type ReadDirFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *ReadDirFS_Expecter) Open(name interface{}) *ReadDirFS_Open_Call {
	return &ReadDirFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *ReadDirFS_Open_Call) Run(run func(name string)) *ReadDirFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ReadDirFS_Open_Call) Return(_a0 fs.File, _a1 error) *ReadDirFS_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReadDirFS_Open_Call) RunAndReturn(run func(string) (fs.File, error)) *ReadDirFS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function with given fields: name
func (_m *ReadDirFS) ReadDir(name string) ([]fs.DirEntry, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadDirFS_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type ReadDirFS_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *ReadDirFS_Expecter) ReadDir(name interface{}) *ReadDirFS_ReadDir_Call {
	return &ReadDirFS_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *ReadDirFS_ReadDir_Call) Run(run func(name string)) *ReadDirFS_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ReadDirFS_ReadDir_Call) Return(_a0 []fs.DirEntry, _a1 error) *ReadDirFS_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReadDirFS_ReadDir_Call) RunAndReturn(run func(string) ([]fs.DirEntry, error)) *ReadDirFS_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewReadDirFS creates a new instance of ReadDirFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadDirFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadDirFS {
	mock := &ReadDirFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
