#!/bin/bash
# Wrapper to run greypi inside the Docker container
# Usage: ./cabin-pi [args...]

# must match dockerfile
export CONTAINER_HOME=/home/ai_agent

exec docker compose exec agent greypi "$@"
