# Generated by cabin authoring. Adapt FROM to your project base image.
FROM ubuntu:24.04

ARG OPENCODE_VERSION=1.4.9

# Install all required packages in one step
RUN apt-get update && apt-get install -y \
    git \
    iproute2 \
    sqlite3 \
    curl \
    vim \
    ca-certificates \
    bash-completion \
    less \
    bubblewrap \
    socat \
    strace \
    && rm -rf /var/lib/apt/lists/*

# Copy the materialized fragments to a build dir and run the numbered install steps
COPY .deps/ /opt/ai-cabin-deps/
RUN /bin/sh /opt/ai-cabin-deps/install.sh \
 && rm -rf /opt/ai-cabin-deps
ENTRYPOINT ["/docker-entrypoint.sh"]

# User setup: the image's default `ubuntu` user (uid 1000) matches the host uid,
# so the bind-mounted dirs (cache, go, desk) are writable. No extra user is created.
USER ubuntu
WORKDIR /home/ubuntu

# Add a greywall sandbox indicator to the prompt
RUN echo 'if [ "$GREYWALL_SANDBOX" = "1" ]; then debian_chroot="🔒"; fi' >> /home/ubuntu/.bashrc

# Create future mount-points so their owner is the default user
RUN mkdir -p .local/share .local/state .local/bin .cache .config/greywall desk go
# Agent opencode: web UI (install.d/50-opencode reads OPENCODE_VERSION)
RUN mkdir -p .config/opencode
EXPOSE 9090
CMD ["opencode", "web", "--port", "9090", "--hostname", "0.0.0.0"]

